DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS matches CASCADE;

CREATE TABLE users (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL
);

CREATE TABLE matches (
  id SERIAL PRIMARY KEY NOT NULL,
  restaurant VARCHAR(12) NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  partner_id INTEGER REFERENCES users(id) ON DELETE CASCADE
);